---
title: "PutAllTogether"
author: "ismayil"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
x1<- read.csv("commentsUK.csv")
x1$likes<-NULL
x1$replies<-NULL
x$comment_text

library(dplyr)

colnames(x1) <- c("vidoe_id", "comment")

x2<- read.csv("commentsUS.csv")
x2$likes<-NULL
x2$replies<-NULL

colnames(x2) <- c("vidoe_id", "comment")
x3<- read.csv("commedy_comment.csv")
x<-rbind(x1,x2)


 x4<- read.csv("ALLcomments.csv")
 x4$X<-NULL
 head(x4)

 x5<- read.csv("music.csv")

 x5$X<-NULL
 x5$X.1<-NULL
  colnames(x5) <- c("vidoe_id", "comment")
# x6<- read.csv("Sports.csv")
# x7<- read.csv("pets.csv")
# x8<- read.csv("Pets_Animals2019.csv")
#x9<- read.csv("music_pop.csv")
#x10<- read.csv("music_song_clip.csv")
# x11<- read.csv("music2019.csv")
# x12<- read.csv("offcialMusic.csv")
# x13<- read.csv("summer_chill_mix_2019.csv")
# x14<- read.csv("summer_mix_2017.csv")
# x15<- read.csv("workout_music_pop.csv")
x<-rbind(x4,x3,x5)
y<-na.omit(x)
write.csv(x,"ALLcomments.csv")
```

